# Cores
BG_COLOR = "#F0F2F5"
BUTTON_COLOR = "#2D88FF"
BUTTON_HOVER_COLOR = "#1A6FEB"
TEXT_COLOR = "#1F1F1F"
BORDER_COLOR = "#D1D5DB"
CELL_COLOR = "#E8EAED"

# Fontes
FONT_PRIMARY = ("Segoe UI", 12)
FONT_SECONDARY = ("Segoe UI", 10)

TIMEOUT = 30
GRID_SIZE = 9